// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MinistryMines.Models;

namespace MinistryMines.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20220517102137_k1")]
    partial class k1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3");

            modelBuilder.Entity("MinistryMines.Models.District", b =>
                {
                    b.Property<int>("District_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("District_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("State_Id")
                        .HasColumnType("int");

                    b.HasKey("District_Id");

                    b.HasIndex("State_Id");

                    b.ToTable("tbl_District");
                });

            modelBuilder.Entity("MinistryMines.Models.District2", b =>
                {
                    b.Property<int>("Dis_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Dis_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("State2S_Id")
                        .HasColumnType("int");

                    b.HasKey("Dis_Id");

                    b.HasIndex("State2S_Id");

                    b.ToTable("tbl_District2");
                });

            modelBuilder.Entity("MinistryMines.Models.State", b =>
                {
                    b.Property<int>("State_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("St_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("State_Id");

                    b.ToTable("tbl_State");
                });

            modelBuilder.Entity("MinistryMines.Models.State2", b =>
                {
                    b.Property<int>("S_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("State_Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("S_Id");

                    b.ToTable("tbl_State2");
                });

            modelBuilder.Entity("MinistryMines.Models.Title", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("TitleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_Title");
                });

            modelBuilder.Entity("MinistryMines.Models.User_Detail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("address_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("district_1")
                        .HasColumnType("int");

                    b.Property<int>("district_2")
                        .HasColumnType("int");

                    b.Property<DateTime>("dob")
                        .HasColumnType("datetime2");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("state_1")
                        .HasColumnType("int");

                    b.Property<int>("state_2")
                        .HasColumnType("int");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("tbl_User_Details");
                });

            modelBuilder.Entity("MinistryMines.Models.District", b =>
                {
                    b.HasOne("MinistryMines.Models.State", "State")
                        .WithMany()
                        .HasForeignKey("State_Id");

                    b.Navigation("State");
                });

            modelBuilder.Entity("MinistryMines.Models.District2", b =>
                {
                    b.HasOne("MinistryMines.Models.State2", "State2")
                        .WithMany()
                        .HasForeignKey("State2S_Id");

                    b.Navigation("State2");
                });
#pragma warning restore 612, 618
        }
    }
}
